# Generated by Django 5.0.1 on 2024-01-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255)),
                ('email', models.CharField(editable=False, max_length=100)),
                ('bank_account', models.CharField(editable=False, max_length=100)),
                ('photo', models.TextField(editable=False)),
                ('bank_pin', models.CharField(editable=False, max_length=10)),
            ],
        ),
    ]
