# Generated by Django 5.0.1 on 2024-01-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encry_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankinformation',
            name='ref',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
