# Generated by Django 5.0.1 on 2024-01-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encry_data', '0002_userbankinformation_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankinformation',
            name='bank_account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userbankinformation',
            name='bank_pin',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userbankinformation',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userbankinformation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userbankinformation',
            name='photo',
            field=models.TextField(),
        ),
    ]
